apiVersion: v1
kind: ConfigMap
metadata:
  name: rvstore-order-sim-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: compose

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvstore-order-sim
  labels:
    app: rvstore-order-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-order-sim
  template:
    metadata:
      labels:
        app: rvstore-order-sim
    spec:
      containers:
      - name: rvstore-order-sim
        image: public.ecr.aws/e7e6w2e3/rvstore-order-simulator
        envFrom:
        - configMapRef:
            name: rvstore-order-sim-config

---

apiVersion: v1
kind: Service
metadata:
  name: rvstore-order-sim
spec:
  selector:
    app: rvstore-order-sim
  ports:
    - protocol: TCP
      port: 80
