apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvstore-auth-api
  labels:
    app: rvstore-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-auth-api
  template:
    metadata:
      labels:
        app: rvstore-auth-api
    spec:
      containers:
      - name: rrvstore-auth-api
        image: public.ecr.aws/e7e6w2e3/rvstore-auth-api

---

apiVersion: v1
kind: Service
metadata:
  name: rvstore-auth-api
spec:
  selector:
    app: rvstore-auth-api
  ports:
  - protocol: TCP
    port: 9003
    nodePort: 30081
  type: NodePort
