apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: secret
  test-file.txt: |
    "this is a test file"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        envFrom:
        - configMapRef:
            name: mongodb-config
        volumeMounts:
        - name: config-volume
          mountPath: /config
        ports:
        - containerPort: 27017
      volumes:
        - name: config-volume
          configMap:
            name: mongodb-config
