apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-container-resources
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container-resources
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "64Mi"
        ephemeral-storage: "50Mi"
      limits:
        cpu: "400m"
        memory: "128Mi"
        ephemeral-storage: "100Mi"
