apiVersion: v1
kind: ConfigMap
metadata:
  name: rvstore-orders-mongodb-config
  namespace: default
data:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvstore-orders-mongodb
  labels:
    app: rvstore-orders-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-orders-mongodb
  template:
    metadata:
      labels:
        app: rvstore-orders-mongodb
    spec:
      containers:
      - name: rvstore-orders-mongodb
        image: public.ecr.aws/e7e6w2e3/rvstore-mongo
        envFrom:
        - configMapRef:
            name: rvstore-orders-mongodb-config
        volumeMounts:
        - name: rvstore-orders-mongodb-data-volume
          mountPath: /data/db
      volumes:
        - name: rvstore-orders-mongodb-data-volume

---

apiVersion: v1
kind: Service
metadata:
  name: rvstore-orders-mongodb
spec:
  selector:
    app: rvstore-orders-mongodb
  ports:
  - protocol: TCP
    port: 27017
    nodePort: 30083
  type: NodePort
