apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvstore-ui
  labels:
    app: rvstore-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-ui
  template:
    metadata:
      labels:
        app: rvstore-ui
    spec:
      containers:
      - name: rvstore-ui
        image: public.ecr.aws/e7e6w2e3/rvstore-ui

---

apiVersion: v1
kind: Service
metadata:
  name: rvstore-ui
spec:
  selector:
    app: rvstore-ui
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
