apiVersion: v1
kind: ConfigMap
metadata:
  name: rvstore-api-gateway-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: compose

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvstore-api-gateway
  labels:
    app: rvstore-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rvstore-api-gateway
  template:
    metadata:
      labels:
        app: rvstore-api-gateway
    spec:
      containers:
      - name: rvstore-api-gateway
        image: public.ecr.aws/e7e6w2e3/rvstore-gateway-service
        envFrom:
        - configMapRef:
            name: rvstore-api-gateway-config

---

apiVersion: v1
kind: Service
metadata:
  name: rvstore-api-gateway
spec:
  selector:
    app: rvstore-api-gateway
  ports:
  - protocol: TCP
    port: 9000
    nodePort: 30090
  type: NodePort
